# Generated by Django 2.0.3 on 2018-04-03 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20180402_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='build_pizza',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='built_pizzas_in_cart', to='orders.Cart'),
        ),
        migrations.AlterField(
            model_name='build_pizza',
            name='pizzatype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='total_built_pizzas', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='build_pizza',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='built_pizzas_in_cart', to='orders.Order'),
        ),
    ]
