# Generated by Django 2.0.3 on 2018-04-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180403_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='salade',
        ),
        migrations.AddField(
            model_name='menu',
            name='dinnerplatter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Dinnerplatter'),
        ),
        migrations.AddField(
            model_name='menu',
            name='pasta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='menu',
            name='pizza',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='menu',
            name='salad',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='menu',
            name='subs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Subs'),
        ),
    ]
