# Generated by Django 2.0.3 on 2018-04-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180403_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build_subs',
            old_name='subtype',
            new_name='substype',
        ),
    ]
