# Generated by Django 2.0.3 on 2018-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180404_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='build_subs',
            name='extracheese',
            field=models.IntegerField(default=0),
        ),
    ]
