# Generated by Django 2.0.3 on 2018-04-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_order_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_info',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
